### ISSUE TITLE
Ngb-Tabset TabChange not showing updated activeID

### ISSUE THREAD

**Issue by lenichols** [ng-bootstrap/ng-bootstrap#3326]
I have implemented (onTabChange)="ts.activeId" and I am getting an id but it is not updating on the first click. It's weird, the first click always returns tab-set-0 even if i click on tab-set-2 etc on the first click. The behavior seems intermittent.

I even tried to pass onTabChange the $event and even those values vary. I've searched but am unable to figure out why the correct activeTab will not just show. What could I be doing wrong?

**Comment by miki995** [comment]
Same for me, first click nothing happens, only on second click.

The tabChange event is firing correct id for me because I've implemented them myself.
How can we solve not activating conent on first click?

**Comment by benouat** [comment]
Hey @lenichols 

Could you please provide a Stackblitz to illustrate the behaviour you describe. I think I don't get the overall idea...

PS: Stackbliz is still broken if you start from our demo site.... You can start and fork that [one](https://stackblitz.com/edit/angular-6empbj)

**Comment by maxokorokov** [comment]
Closing as no news, please reopen if necessary.
