### ISSUE TITLE
ngbpopover floats on page size change

### ISSUE THREAD

**Issue by chandresh87** [ng-bootstrap/ng-bootstrap#3382]
When using container="body" , open the popover and change the screen size then popover don't stick to the link which has opened the popover.

This behavior can be replicated on the https://ngbootstrap.github.io/#/components/popover/examples as well.

I have tested this in chrome.
steps to replicate:

click to open
change the screen size.
popover will start to float on the page.

**Comment by fbasso** [comment]
Thanks for reporting @chandresh87 ! It should be fixed with #3245.

**Comment by chandresh87** [comment]
could you please tell me which version has this fix? I am using 4.2.1

**Comment by chandresh87** [comment]
I tried using the 4.2.2 and still have the same issue. could you please look into this?

**Comment by fbasso** [comment]
It is not released yet. Unfortunately, I can't give you a date, but we'll try to do it soon.

**Comment by kamlesh0606** [comment]
Any Update ?
