### ISSUE TITLE
strictTemplates in Angular 9 generates error

### ISSUE THREAD

**Issue by andzejsw** [ng-bootstrap/ng-bootstrap#3628]
Enabling the new strictTemplates flag in Angular 9's compiler options generates the following build error:
`This likely means that the library (@ng-bootstrap/ng-bootstrap) which declares NgbModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

I am using latest ng-bootstrap.

**Comment by maxokorokov** [comment]
Please take a look at the [Getting Help](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/README.md#getting-help) section in documentation and use the appropriate support channel.

If you believe you've found a bug in this library then please:
- fill in the issue template correctly
- provide a way to reproduce it for is

@andzejsw please understand that by reading what you've provided we cannot guess what exactly is not working on your side. You're the first person reporting this kind of issue with this error message.

Also please check #3619 and the solution to it that have just been merged into master today.
You could either try the master version or wait for `6.0.1` with `strictTemplates` support.

**Comment by andzejsw** [comment]
Same error appears for `@angular` components: https://github.com/angular/components/issues/18637

And i already mentioned, what i know. Error appears only when i am building app with `strictTemplates` flag enabled in `tsconfig.json` file.

**Comment by andzejsw** [comment]
Today I updated all dependencies and error disappeared. Is it fixed. Can anyone confirm?

**Comment by BrutalCSkakan** [comment]
This is broken for Angular 9, I get the same error.

**Comment by vaibhavphutane** [comment]
Work around 
set strictInjectionParameters to `false` in `tsconfig.json`

` "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": false
  }`

**Comment by filipemcg** [comment]
Bumping this thread as this is still an issue:
```json
"dependencies": {
    "@angular/animations": "~9.0.5",
    "@angular/cdk": "^9.1.1",
    "@angular/common": "~9.0.5",
    "@angular/compiler": "~9.0.5",
    "@angular/core": "~9.0.5",
    "@angular/forms": "~9.0.5",
    "@angular/material": "^9.1.1",
    "@angular/platform-browser": "~9.0.5",
    "@angular/platform-browser-dynamic": "~9.0.5",
    "@angular/router": "~9.0.5",
...
"devDependencies": {
    "@angular-devkit/build-angular": "~0.900.5",
    "@angular/cli": "~9.0.5",
    "@angular/compiler-cli": "~9.0.5",
    "@angular/language-service": "~9.0.5",
```

@vaibhavphutane, setting `strictInjectionParameters` to `false` did not worked around the issue. Did you run any special command after setting that option to false?

@andzejsw, can you elaborate on what dependencies you have updated? That could help understand the issue.

**Comment by vaibhavphutane** [comment]
@filipemcg It should work
can you try setting `strictTemplates` to `false`
It will not check for Injectables 
please refer  
https://angular.io/guide/template-typecheck

**Comment by bbarry** [comment]
I've had this error several times during the process of updating recently.

It has gone away each time for me by deleting my ./dist directory, package-lock.json and node_modules directory

**Comment by maxokorokov** [comment]
From multiple reports looks like it is the caching issue, so clearing the node_modules, updating the lock file should help. 

`strictTemplates` problem usage for issues like #3619 should have been addressed in `6.0.1`.

I'm going to close this, please comment/reopen if necessary.

**Comment by olcaydaser** [comment]
"strictInjectionParameters": false in tsconfig.json looks like a temp solution.

**Comment by amanpurohit** [comment]
Still cannot fix this. I am using the following versions:

> Angular CLI: 9.1.6
> ng-bootstrap": 6.1.0

I changed the property `strictInjectionParameters` to `false` and removed the node_modules directory as well as the package-lock.json file.

**Comment by chrisreed01** [comment]
Had the same issue when installing.  Missed a step in the instructions. followed the below and it compiled fine.

@angular/localize polyfill
If you're using Angular ≥ 9.0.0 and ng-bootstrap ≥ 6.0.0, you also have to install the @angular/localize polyfill:

ng add @angular/localize

**Comment by iballi2017** [comment]
1. Go to to the CLI
2. Press CTRL + C
3. Press Y
4. Re-serve your application again
The error should disappear this time
